//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Assetobj_prefab
    {
        public const string BundleName = "assetobj_prefab";
        public const string ASSETOBJ = "assetobj";
    }
    public class Audio
    {
        public const string BundleName = "audio";
    }
    public class Battlescene_unity
    {
        public const string BundleName = "battlescene_unity";
        public const string BATTLESCENE = "battlescene";
    }
    public class Clack_minimal_wav
    {
        public const string BundleName = "clack_minimal_wav";
        public const string CLACK_MINIMAL = "clack_minimal";
    }
    public class Click3_wav
    {
        public const string BundleName = "click3_wav";
        public const string CLICK3 = "click3";
    }
    public class Coarseclick_minimal_wav
    {
        public const string BundleName = "coarseclick_minimal_wav";
        public const string COARSECLICK_MINIMAL = "coarseclick_minimal";
    }
    public class Funnyclick_minimal_wav
    {
        public const string BundleName = "funnyclick_minimal_wav";
        public const string FUNNYCLICK_MINIMAL = "funnyclick_minimal";
    }
    public class Ping_minimal_wav
    {
        public const string BundleName = "ping_minimal_wav";
        public const string PING_MINIMAL = "ping_minimal";
    }
    public class Sceneres_unity
    {
        public const string BundleName = "sceneres_unity";
        public const string SCENERES = "sceneres";
    }
    public class Spacey_wav
    {
        public const string BundleName = "spacey_wav";
        public const string SPACEY = "spacey";
    }
    public class Spriteatlas_spriteatlas
    {
        public const string BundleName = "spriteatlas_spriteatlas";
        public const string SPRITEATLAS = "spriteatlas";
    }
    public class Testimage_png
    {
        public const string BundleName = "testimage_png";
        public const string TESTIMAGE = "testimage";
    }
    public class Textureexample1_png
    {
        public const string BundleName = "textureexample1_png";
        public const string TEXTUREEXAMPLE1 = "textureexample1";
    }
    public class Uimain_prefab
    {
        public const string BundleName = "uimain_prefab";
        public const string UIMAIN = "uimain";
    }
    public class Uimenu_prefab
    {
        public const string BundleName = "uimenu_prefab";
        public const string UIMENU = "uimenu";
    }
    public class Uiselectstage_prefab
    {
        public const string BundleName = "uiselectstage_prefab";
        public const string UISELECTSTAGE = "uiselectstage";
    }
    public class Uisettings_prefab
    {
        public const string BundleName = "uisettings_prefab";
        public const string UISETTINGS = "uisettings";
    }
    public class Uistaff_prefab
    {
        public const string BundleName = "uistaff_prefab";
        public const string UISTAFF = "uistaff";
    }
    public class Uistageclear_prefab
    {
        public const string BundleName = "uistageclear_prefab";
        public const string UISTAGECLEAR = "uistageclear";
    }
}
