using UnityEngine;
namespace QFramework.Example {
    public class StageDefine: Singleton<StageDefine>  {


        public struct StageInfo {
            public string StageName;
            public OrderType[] orders;
            public ItemInfo[] Items;
        }

        public struct ItemInfo {
            public Vector3 Pos;
            public ItemType ItemType;
        }

        public StageInfo[] stages = new StageInfo[15];
        public override void OnSingletonInit() {
            var stage = stages[0];
            stage.StageName = "始于足下";
            stage.orders = new OrderType[1];
            stage.orders[0] = OrderType.MOVE_FORWARD;
            stage.Items = new ItemInfo[1];
            stage.Items[0].Pos.Set(-4, 0, -3); stage.Items[0].ItemType = ItemType.GRASS;
            stages[0] = stage;

            stage = stages[1];
            stage.StageName = "事不过三";
            stage.orders = new OrderType[1];
            stage.orders[0] = OrderType.MOVE_FORWARD;
            stage.Items = new ItemInfo[3];
            stage.Items[0].Pos.Set(-4, 0, -3); stage.Items[0].ItemType = ItemType.GRASS;
            stage.Items[1].Pos.Set(-4, 0, -2); stage.Items[1].ItemType = ItemType.GRASS;
            stage.Items[2].Pos.Set(-4, 0, -1); stage.Items[2].ItemType = ItemType.GRASS;
            stages[1] = stage;


            stage = stages[2];
            stage.StageName = "蓦然回首";
            stage.orders = new OrderType[2];
            stage.orders[0] = OrderType.MOVE_FORWARD;
            stage.orders[1] = OrderType.TURN_RIGHT;
            stage.Items = new ItemInfo[2];
            stage.Items[0].Pos.Set(-4, 0, -3); stage.Items[0].ItemType = ItemType.GRASS;
            stage.Items[1].Pos.Set(-3, 0, -3); stage.Items[1].ItemType = ItemType.GRASS;
            stages[2] = stage;


            stage = stages[3];
            stage.StageName = "世界正中";
            stage.orders = new OrderType[3];
            stage.orders[0] = OrderType.MOVE_FORWARD;
            stage.orders[1] = OrderType.TURN_RIGHT;
            stage.orders[2] = OrderType.TRUN_LEFT;
            stage.Items = new ItemInfo[1];
            stage.Items[0].Pos.Set(0, 0, 0); stage.Items[0].ItemType = ItemType.GEM;
            stages[3] = stage;

            stage = stages[4];
            stage.StageName = "曲径通幽";
            stage.orders = new OrderType[5];
            stage.orders[0] = OrderType.MOVE_FORWARD;
            stage.orders[1] = OrderType.TURN_RIGHT;
            stage.orders[2] = OrderType.TRUN_LEFT;
            stage.orders[3] = OrderType.LOOP_MAIN;
            stage.orders[4] = OrderType.LOOP_TAIL;
            stage.Items = new ItemInfo[8];
            stage.Items[0].Pos.Set(-3, -0.2f, -3); stage.Items[0].ItemType = ItemType.GRASS;
            stage.Items[1].Pos.Set(-2, -0.2f, -2); stage.Items[1].ItemType = ItemType.GRASS;
            stage.Items[2].Pos.Set(-1, -0.2f, -1); stage.Items[2].ItemType = ItemType.GRASS;
            stage.Items[3].Pos.Set(0, -0.2f, 0); stage.Items[3].ItemType = ItemType.GRASS;
            stage.Items[4].Pos.Set(1, -0.2f, 1); stage.Items[4].ItemType = ItemType.GRASS;
            stage.Items[5].Pos.Set(2, -0.2f, 2); stage.Items[5].ItemType = ItemType.GRASS;
            stage.Items[6].Pos.Set(3, -0.2f, 3); stage.Items[6].ItemType = ItemType.GRASS;
            stage.Items[7].Pos.Set(4, -0.2f, 4); stage.Items[7].ItemType = ItemType.GEM;
            stages[4] = stage;
            //============================================================================================

            stage = stages[5];
            stage.StageName = "挡路石";
            stage.orders = new OrderType[5];
            stage.orders[0] = OrderType.MOVE_FORWARD;
            stage.orders[1] = OrderType.TURN_RIGHT;
            stage.orders[2] = OrderType.TRUN_LEFT;
            stage.orders[3] = OrderType.LOOP_MAIN;
            stage.orders[4] = OrderType.LOOP_TAIL;
            stage.Items = new ItemInfo[17];
            stage.Items[0].Pos.Set(-3, -0.2f, -3); stage.Items[0].ItemType = ItemType.ROCK;
            stage.Items[1].Pos.Set(-2, -0.2f, -3); stage.Items[1].ItemType = ItemType.ROCK;
            stage.Items[2].Pos.Set(-1, -0.2f, -3); stage.Items[2].ItemType = ItemType.ROCK;
            stage.Items[3].Pos.Set(0, -0.2f, -3); stage.Items[3].ItemType = ItemType.ROCK;
            stage.Items[4].Pos.Set(1, -0.2f, -3); stage.Items[4].ItemType = ItemType.ROCK;
            stage.Items[5].Pos.Set(2, -0.2f, -3); stage.Items[5].ItemType = ItemType.ROCK;
            stage.Items[6].Pos.Set(3, -0.2f, -3); stage.Items[6].ItemType = ItemType.ROCK;
            stage.Items[7].Pos.Set(-4, -0.2f, -3); stage.Items[7].ItemType = ItemType.ROCK;
            stage.Items[8].Pos.Set(4, -0.2f, -1); stage.Items[8].ItemType = ItemType.ROCK;
            stage.Items[9].Pos.Set(-3, -0.2f, -1); stage.Items[9].ItemType = ItemType.ROCK;
            stage.Items[10].Pos.Set(-2, -0.2f, -1); stage.Items[10].ItemType = ItemType.ROCK;
            stage.Items[11].Pos.Set(-1, -0.2f, -1); stage.Items[11].ItemType = ItemType.ROCK;
            stage.Items[12].Pos.Set(0, -0.2f, -1); stage.Items[12].ItemType = ItemType.ROCK;
            stage.Items[13].Pos.Set(1, -0.2f, -1); stage.Items[13].ItemType = ItemType.ROCK;
            stage.Items[14].Pos.Set(2, -0.2f, -1); stage.Items[14].ItemType = ItemType.ROCK;
            stage.Items[15].Pos.Set(3, -0.2f, -1); stage.Items[15].ItemType = ItemType.ROCK;
            stage.Items[16].Pos.Set(-4, -0.2f, 1); stage.Items[16].ItemType = ItemType.GEM;
            stages[5] = stage;

            stage = stages[6];
            stage.StageName = "唯一选择";
            stage.orders = new OrderType[5];
            stage.orders[0] = OrderType.MOVE_FORWARD;
            stage.orders[1] = OrderType.TURN_RIGHT;
            stage.orders[2] = OrderType.TRUN_LEFT;
            stage.orders[3] = OrderType.LOOP_MAIN;
            stage.orders[4] = OrderType.LOOP_TAIL;
            stage.Items = new ItemInfo[30];
            stage.Items[0].Pos.Set(-4, 0, 0); stage.Items[0].ItemType = ItemType.ROCK;
            stage.Items[1].Pos.Set(-3, 0, -4); stage.Items[1].ItemType = ItemType.GRASS;
            stage.Items[2].Pos.Set(-3, 0, 0); stage.Items[2].ItemType = ItemType.ROCK;
            stage.Items[3].Pos.Set(-2, 0, -4); stage.Items[3].ItemType = ItemType.GRASS;
            stage.Items[4].Pos.Set(-2, 0, 0); stage.Items[4].ItemType = ItemType.ROCK;
            stage.Items[5].Pos.Set(-1, 0, -4); stage.Items[5].ItemType = ItemType.GRASS;
            stage.Items[6].Pos.Set(-1, 0, 0); stage.Items[6].ItemType = ItemType.ROCK;
            stage.Items[7].Pos.Set(0, 0, -4); stage.Items[7].ItemType = ItemType.ROCK;
            stage.Items[8].Pos.Set(0, 0, -3); stage.Items[8].ItemType = ItemType.ROCK;
            stage.Items[9].Pos.Set(0, 0, -2); stage.Items[9].ItemType = ItemType.ROCK;
            stage.Items[10].Pos.Set(0, 0, -1); stage.Items[10].ItemType = ItemType.ROCK;
            stage.Items[11].Pos.Set(0, 0, 0); stage.Items[11].ItemType = ItemType.ROCK;
            stage.Items[12].Pos.Set(0, 0, 1); stage.Items[12].ItemType = ItemType.ROCK;
            stage.Items[13].Pos.Set(0, 0, 2); stage.Items[13].ItemType = ItemType.ROCK;
            stage.Items[14].Pos.Set(0, 0, 3); stage.Items[14].ItemType = ItemType.ROCK;
            stage.Items[15].Pos.Set(0, 0, 4); stage.Items[15].ItemType = ItemType.ROCK;
            stage.Items[16].Pos.Set(1, 0, -4); stage.Items[16].ItemType = ItemType.GRASS;
            stage.Items[17].Pos.Set(1, 0, 0); stage.Items[17].ItemType = ItemType.ROCK;
            stage.Items[18].Pos.Set(2, 0, -4); stage.Items[18].ItemType = ItemType.GRASS;
            stage.Items[19].Pos.Set(2, 0, -3); stage.Items[19].ItemType = ItemType.GRASS;
            stage.Items[20].Pos.Set(2, 0, -2); stage.Items[20].ItemType = ItemType.GRASS;
            stage.Items[21].Pos.Set(2, 0, -1); stage.Items[21].ItemType = ItemType.GRASS;
            stage.Items[22].Pos.Set(2, 0, 0); stage.Items[22].ItemType = ItemType.ROCK;
            stage.Items[23].Pos.Set(2, 0, 1); stage.Items[23].ItemType = ItemType.GRASS;
            stage.Items[24].Pos.Set(2, 0, 2); stage.Items[24].ItemType = ItemType.GEM;
            stage.Items[25].Pos.Set(2, 0, 3); stage.Items[25].ItemType = ItemType.GEM;
            stage.Items[26].Pos.Set(3, 0, 0); stage.Items[26].ItemType = ItemType.ROCK;
            stage.Items[27].Pos.Set(3, 0, 2); stage.Items[27].ItemType = ItemType.GEM;
            stage.Items[28].Pos.Set(3, 0, 3); stage.Items[28].ItemType = ItemType.GEM;
            stage.Items[29].Pos.Set(4, 0, 0); stage.Items[29].ItemType = ItemType.ROCK;

            stages[6] = stage;

            stage = stages[7];
            stage.StageName = "林荫小道";
            stage.orders = new OrderType[5];
            stage.orders[0] = OrderType.MOVE_FORWARD;
            stage.orders[1] = OrderType.TURN_RIGHT;
            stage.orders[2] = OrderType.TRUN_LEFT;
            stage.orders[3] = OrderType.LOOP_MAIN;
            stage.orders[4] = OrderType.LOOP_TAIL;
            stage.Items = new ItemInfo[31];
            stage.Items[0].Pos.Set(-4, 0, -3); stage.Items[0].ItemType = ItemType.ROCK;
            stage.Items[1].Pos.Set(-3, 0, -3); stage.Items[1].ItemType = ItemType.ROCK;
            stage.Items[2].Pos.Set(-2, 0, -3); stage.Items[2].ItemType = ItemType.ROCK;
            stage.Items[3].Pos.Set(-1, 0, -3); stage.Items[3].ItemType = ItemType.ROCK;
            stage.Items[4].Pos.Set(-1, 0, -2); stage.Items[4].ItemType = ItemType.TREE;
            stage.Items[5].Pos.Set(-1, 0, -1); stage.Items[5].ItemType = ItemType.TREE;
            stage.Items[6].Pos.Set(-1, 0, 0); stage.Items[6].ItemType = ItemType.TREE;
            stage.Items[7].Pos.Set(-1, 0, 1); stage.Items[7].ItemType = ItemType.TREE;
            stage.Items[8].Pos.Set(-1, 0, 2); stage.Items[8].ItemType = ItemType.TREE;
            stage.Items[9].Pos.Set(-1, 0, 3); stage.Items[9].ItemType = ItemType.TREE;
            stage.Items[10].Pos.Set(-1, 0, 4); stage.Items[10].ItemType = ItemType.TREE;
            stage.Items[11].Pos.Set(0, 0, -3); stage.Items[11].ItemType = ItemType.GRASS;
            stage.Items[12].Pos.Set(0, 0, -2); stage.Items[12].ItemType = ItemType.GRASS;
            stage.Items[13].Pos.Set(0, 0, -1); stage.Items[13].ItemType = ItemType.GRASS;
            stage.Items[14].Pos.Set(0, 0, 0); stage.Items[14].ItemType = ItemType.GRASS;
            stage.Items[15].Pos.Set(0, 0, 1); stage.Items[15].ItemType = ItemType.GRASS;
            stage.Items[16].Pos.Set(0, 0, 2); stage.Items[16].ItemType = ItemType.GRASS;
            stage.Items[17].Pos.Set(0, 0, 3); stage.Items[17].ItemType = ItemType.GRASS;
            stage.Items[18].Pos.Set(0, 0, 4); stage.Items[18].ItemType = ItemType.GRASS;
            stage.Items[19].Pos.Set(1, 0, -3); stage.Items[19].ItemType = ItemType.ROCK;
            stage.Items[20].Pos.Set(1, 0, -2); stage.Items[20].ItemType = ItemType.TREE;
            stage.Items[21].Pos.Set(1, 0, -1); stage.Items[21].ItemType = ItemType.TREE;
            stage.Items[22].Pos.Set(1, 0, 0); stage.Items[22].ItemType = ItemType.TREE;
            stage.Items[23].Pos.Set(1, 0, 1); stage.Items[23].ItemType = ItemType.TREE;
            stage.Items[24].Pos.Set(1, 0, 2); stage.Items[24].ItemType = ItemType.TREE;
            stage.Items[25].Pos.Set(1, 0, 3); stage.Items[25].ItemType = ItemType.TREE;
            stage.Items[26].Pos.Set(1, 0, 4); stage.Items[26].ItemType = ItemType.GRASS;
            stage.Items[27].Pos.Set(2, 0, -3); stage.Items[27].ItemType = ItemType.ROCK;
            stage.Items[28].Pos.Set(2, 0, 4); stage.Items[28].ItemType = ItemType.GEM;
            stage.Items[29].Pos.Set(3, 0, -3); stage.Items[29].ItemType = ItemType.ROCK;
            stage.Items[30].Pos.Set(4, 0, -3); stage.Items[30].ItemType = ItemType.ROCK;
            stages[7] = stage;

            stage = stages[8];
            stage.StageName = "禁止通行";
            stage.orders = new OrderType[5];
            stage.orders[0] = OrderType.MOVE_FORWARD;
            stage.orders[1] = OrderType.TURN_RIGHT;
            stage.orders[2] = OrderType.TRUN_LEFT;
            stage.orders[3] = OrderType.LOOP_MAIN;
            stage.orders[4] = OrderType.LOOP_TAIL;
            stage.Items = new ItemInfo[15];
            stage.Items[0].Pos.Set(-3, 0, -2); stage.Items[0].ItemType = ItemType.ROCK;
            stage.Items[1].Pos.Set(-3, 0, 4); stage.Items[1].ItemType = ItemType.ROCK;
            stage.Items[2].Pos.Set(-2, 0, -1); stage.Items[2].ItemType = ItemType.ROCK;
            stage.Items[3].Pos.Set(-2, 0, 3); stage.Items[3].ItemType = ItemType.ROCK;
            stage.Items[4].Pos.Set(-1, 0, 0); stage.Items[4].ItemType = ItemType.ROCK;
            stage.Items[5].Pos.Set(-1, 0, 2); stage.Items[5].ItemType = ItemType.ROCK;
            stage.Items[6].Pos.Set(0, 0, -2); stage.Items[6].ItemType = ItemType.GRASS;
            stage.Items[7].Pos.Set(0, 0, 1); stage.Items[7].ItemType = ItemType.TREE;
            stage.Items[8].Pos.Set(0, 0, 4); stage.Items[8].ItemType = ItemType.GEM;
            stage.Items[9].Pos.Set(1, 0, 0); stage.Items[9].ItemType = ItemType.ROCK;
            stage.Items[10].Pos.Set(1, 0, 2); stage.Items[10].ItemType = ItemType.ROCK;
            stage.Items[11].Pos.Set(2, 0, -1); stage.Items[11].ItemType = ItemType.ROCK;
            stage.Items[12].Pos.Set(2, 0, 3); stage.Items[12].ItemType = ItemType.ROCK;
            stage.Items[13].Pos.Set(3, 0, -2); stage.Items[13].ItemType = ItemType.ROCK;
            stage.Items[14].Pos.Set(3, 0, 4); stage.Items[14].ItemType = ItemType.ROCK;

            stages[8] = stage;

            stage = stages[9];
            stage.StageName = "要微笑";
            stage.orders = new OrderType[5];
            stage.orders[0] = OrderType.MOVE_FORWARD;
            stage.orders[1] = OrderType.TURN_RIGHT;
            stage.orders[2] = OrderType.TRUN_LEFT;
            stage.orders[3] = OrderType.LOOP_MAIN;
            stage.orders[4] = OrderType.LOOP_TAIL;
            stage.Items = new ItemInfo[7];
            stage.Items[0].Pos.Set(-2, 0, 1); stage.Items[0].ItemType = ItemType.GEM;
            stage.Items[1].Pos.Set(-1, 0, -2); stage.Items[1].ItemType = ItemType.TREE;
            stage.Items[2].Pos.Set(0, 0, -3); stage.Items[2].ItemType = ItemType.GRASS;
            stage.Items[3].Pos.Set(0, 0, -1); stage.Items[3].ItemType = ItemType.ROCK;
            stage.Items[4].Pos.Set(0, 0, 0); stage.Items[4].ItemType = ItemType.ROCK;
            stage.Items[5].Pos.Set(1, 0, -2); stage.Items[5].ItemType = ItemType.TREE;
            stage.Items[6].Pos.Set(2, 0, 1); stage.Items[6].ItemType = ItemType.GEM;

            stages[9] = stage;

            stage = stages[10];
            stage.StageName = "一把小伞";
            stage.orders = new OrderType[5];
            stage.orders[0] = OrderType.MOVE_FORWARD;
            stage.orders[1] = OrderType.TURN_RIGHT;
            stage.orders[2] = OrderType.TRUN_LEFT;
            stage.orders[3] = OrderType.LOOP_MAIN;
            stage.orders[4] = OrderType.LOOP_TAIL;
            stage.Items = new ItemInfo[19];
            stage.Items[0].Pos.Set(-3, 0, 1); stage.Items[0].ItemType = ItemType.TREE;
            stage.Items[1].Pos.Set(-2, 0, 2); stage.Items[1].ItemType = ItemType.TREE;
            stage.Items[2].Pos.Set(-1, 0, 1); stage.Items[2].ItemType = ItemType.GEM;
            stage.Items[3].Pos.Set(-1, 0, 2); stage.Items[3].ItemType = ItemType.ROCK;
            stage.Items[4].Pos.Set(-1, 0, 3); stage.Items[4].ItemType = ItemType.TREE;
            stage.Items[5].Pos.Set(0, 0, -4); stage.Items[5].ItemType = ItemType.ROCK;
            stage.Items[6].Pos.Set(0, 0, -3); stage.Items[6].ItemType = ItemType.ROCK;
            stage.Items[7].Pos.Set(0, 0, -2); stage.Items[7].ItemType = ItemType.ROCK;
            stage.Items[8].Pos.Set(0, 0, -1); stage.Items[8].ItemType = ItemType.ROCK;
            stage.Items[9].Pos.Set(0, 0, 0); stage.Items[9].ItemType = ItemType.ROCK;
            stage.Items[10].Pos.Set(0, 0, 1); stage.Items[10].ItemType = ItemType.ROCK;
            stage.Items[11].Pos.Set(0, 0, 2); stage.Items[11].ItemType = ItemType.ROCK;
            stage.Items[12].Pos.Set(0, 0, 3); stage.Items[12].ItemType = ItemType.ROCK;
            stage.Items[13].Pos.Set(0, 0, 4); stage.Items[13].ItemType = ItemType.TREE;
            stage.Items[14].Pos.Set(1, 0, 1); stage.Items[14].ItemType = ItemType.GEM;
            stage.Items[15].Pos.Set(1, 0, 2); stage.Items[15].ItemType = ItemType.ROCK;
            stage.Items[16].Pos.Set(1, 0, 3); stage.Items[16].ItemType = ItemType.TREE;
            stage.Items[17].Pos.Set(2, 0, 2); stage.Items[17].ItemType = ItemType.TREE;
            stage.Items[18].Pos.Set(3, 0, 1); stage.Items[18].ItemType = ItemType.TREE;
            stages[10] = stage;

            stage = stages[11];
            stage.StageName = "捷径";
            stage.orders = new OrderType[3];
            stage.orders[0] = OrderType.MOVE_FORWARD;
            stage.orders[1] = OrderType.LOOP_MAIN;
            stage.orders[2] = OrderType.LOOP_TAIL;
            stage.Items = new ItemInfo[7];
            stage.Items[0].Pos.Set(-4, 0, -3); stage.Items[0].ItemType = ItemType.TREE;
            stage.Items[1].Pos.Set(-3, 0, -3); stage.Items[1].ItemType = ItemType.GRASS;
            stage.Items[2].Pos.Set(-2, 0, -2); stage.Items[2].ItemType = ItemType.GRASS;
            stage.Items[3].Pos.Set(-1, 0, -1); stage.Items[3].ItemType = ItemType.GRASS;
            stage.Items[4].Pos.Set(0, 0, 0); stage.Items[4].ItemType = ItemType.GRASS;
            stage.Items[5].Pos.Set(1, 0, 1); stage.Items[5].ItemType = ItemType.GRASS;
            stage.Items[6].Pos.Set(2, 0, 2); stage.Items[6].ItemType = ItemType.GEM;
            stages[11] = stage;

            stage = stages[12];
            stage.StageName = "烤烤显卡";
            stage.orders = new OrderType[5];
            stage.orders[0] = OrderType.MOVE_FORWARD;
            stage.orders[1] = OrderType.TURN_RIGHT;
            stage.orders[2] = OrderType.TRUN_LEFT;
            stage.orders[3] = OrderType.LOOP_MAIN;
            stage.orders[4] = OrderType.LOOP_TAIL;
            stage.Items = new ItemInfo[81];
            stage.Items[0].Pos.Set(-4, 0, -4); stage.Items[0].ItemType = ItemType.GRASS;
            stage.Items[1].Pos.Set(-4, 0, -3); stage.Items[1].ItemType = ItemType.GRASS;
            stage.Items[2].Pos.Set(-4, 0, -2); stage.Items[2].ItemType = ItemType.GRASS;
            stage.Items[3].Pos.Set(-4, 0, -1); stage.Items[3].ItemType = ItemType.GRASS;
            stage.Items[4].Pos.Set(-4, 0, 0); stage.Items[4].ItemType = ItemType.GRASS;
            stage.Items[5].Pos.Set(-4, 0, 1); stage.Items[5].ItemType = ItemType.GRASS;
            stage.Items[6].Pos.Set(-4, 0, 2); stage.Items[6].ItemType = ItemType.GRASS;
            stage.Items[7].Pos.Set(-4, 0, 3); stage.Items[7].ItemType = ItemType.GRASS;
            stage.Items[8].Pos.Set(-4, 0, 4); stage.Items[8].ItemType = ItemType.GRASS;
            stage.Items[9].Pos.Set(-3, 0, -4); stage.Items[9].ItemType = ItemType.GRASS;
            stage.Items[10].Pos.Set(-3, 0, -3); stage.Items[10].ItemType = ItemType.GEM;
            stage.Items[11].Pos.Set(-3, 0, -2); stage.Items[11].ItemType = ItemType.GEM;
            stage.Items[12].Pos.Set(-3, 0, -1); stage.Items[12].ItemType = ItemType.GEM;
            stage.Items[13].Pos.Set(-3, 0, 0); stage.Items[13].ItemType = ItemType.GEM;
            stage.Items[14].Pos.Set(-3, 0, 1); stage.Items[14].ItemType = ItemType.GEM;
            stage.Items[15].Pos.Set(-3, 0, 2); stage.Items[15].ItemType = ItemType.GEM;
            stage.Items[16].Pos.Set(-3, 0, 3); stage.Items[16].ItemType = ItemType.GEM;
            stage.Items[17].Pos.Set(-3, 0, 4); stage.Items[17].ItemType = ItemType.GRASS;
            stage.Items[18].Pos.Set(-2, 0, -4); stage.Items[18].ItemType = ItemType.GRASS;
            stage.Items[19].Pos.Set(-2, 0, -3); stage.Items[19].ItemType = ItemType.GEM;
            stage.Items[20].Pos.Set(-2, 0, -2); stage.Items[20].ItemType = ItemType.GEM;
            stage.Items[21].Pos.Set(-2, 0, -1); stage.Items[21].ItemType = ItemType.GEM;
            stage.Items[22].Pos.Set(-2, 0, 0); stage.Items[22].ItemType = ItemType.GEM;
            stage.Items[23].Pos.Set(-2, 0, 1); stage.Items[23].ItemType = ItemType.GEM;
            stage.Items[24].Pos.Set(-2, 0, 2); stage.Items[24].ItemType = ItemType.GEM;
            stage.Items[25].Pos.Set(-2, 0, 3); stage.Items[25].ItemType = ItemType.GEM;
            stage.Items[26].Pos.Set(-2, 0, 4); stage.Items[26].ItemType = ItemType.GRASS;
            stage.Items[27].Pos.Set(-1, 0, -4); stage.Items[27].ItemType = ItemType.GRASS;
            stage.Items[28].Pos.Set(-1, 0, -3); stage.Items[28].ItemType = ItemType.GEM;
            stage.Items[29].Pos.Set(-1, 0, -2); stage.Items[29].ItemType = ItemType.GEM;
            stage.Items[30].Pos.Set(-1, 0, -1); stage.Items[30].ItemType = ItemType.GEM;
            stage.Items[31].Pos.Set(-1, 0, 0); stage.Items[31].ItemType = ItemType.GEM;
            stage.Items[32].Pos.Set(-1, 0, 1); stage.Items[32].ItemType = ItemType.GEM;
            stage.Items[33].Pos.Set(-1, 0, 2); stage.Items[33].ItemType = ItemType.GEM;
            stage.Items[34].Pos.Set(-1, 0, 3); stage.Items[34].ItemType = ItemType.GEM;
            stage.Items[35].Pos.Set(-1, 0, 4); stage.Items[35].ItemType = ItemType.GRASS;
            stage.Items[36].Pos.Set(0, 0, -4); stage.Items[36].ItemType = ItemType.GRASS;
            stage.Items[37].Pos.Set(0, 0, -3); stage.Items[37].ItemType = ItemType.GEM;
            stage.Items[38].Pos.Set(0, 0, -2); stage.Items[38].ItemType = ItemType.GEM;
            stage.Items[39].Pos.Set(0, 0, -1); stage.Items[39].ItemType = ItemType.GEM;
            stage.Items[40].Pos.Set(0, 0, 0); stage.Items[40].ItemType = ItemType.GEM;
            stage.Items[41].Pos.Set(0, 0, 1); stage.Items[41].ItemType = ItemType.GEM;
            stage.Items[42].Pos.Set(0, 0, 2); stage.Items[42].ItemType = ItemType.GEM;
            stage.Items[43].Pos.Set(0, 0, 3); stage.Items[43].ItemType = ItemType.GEM;
            stage.Items[44].Pos.Set(0, 0, 4); stage.Items[44].ItemType = ItemType.GRASS;
            stage.Items[45].Pos.Set(1, 0, -4); stage.Items[45].ItemType = ItemType.GRASS;
            stage.Items[46].Pos.Set(1, 0, -3); stage.Items[46].ItemType = ItemType.GEM;
            stage.Items[47].Pos.Set(1, 0, -2); stage.Items[47].ItemType = ItemType.GEM;
            stage.Items[48].Pos.Set(1, 0, -1); stage.Items[48].ItemType = ItemType.GEM;
            stage.Items[49].Pos.Set(1, 0, 0); stage.Items[49].ItemType = ItemType.GEM;
            stage.Items[50].Pos.Set(1, 0, 1); stage.Items[50].ItemType = ItemType.GEM;
            stage.Items[51].Pos.Set(1, 0, 2); stage.Items[51].ItemType = ItemType.GEM;
            stage.Items[52].Pos.Set(1, 0, 3); stage.Items[52].ItemType = ItemType.GEM;
            stage.Items[53].Pos.Set(1, 0, 4); stage.Items[53].ItemType = ItemType.GRASS;
            stage.Items[54].Pos.Set(2, 0, -4); stage.Items[54].ItemType = ItemType.GRASS;
            stage.Items[55].Pos.Set(2, 0, -3); stage.Items[55].ItemType = ItemType.GEM;
            stage.Items[56].Pos.Set(2, 0, -2); stage.Items[56].ItemType = ItemType.GEM;
            stage.Items[57].Pos.Set(2, 0, -1); stage.Items[57].ItemType = ItemType.GEM;
            stage.Items[58].Pos.Set(2, 0, 0); stage.Items[58].ItemType = ItemType.GEM;
            stage.Items[59].Pos.Set(2, 0, 1); stage.Items[59].ItemType = ItemType.GEM;
            stage.Items[60].Pos.Set(2, 0, 2); stage.Items[60].ItemType = ItemType.GEM;
            stage.Items[61].Pos.Set(2, 0, 3); stage.Items[61].ItemType = ItemType.GEM;
            stage.Items[62].Pos.Set(2, 0, 4); stage.Items[62].ItemType = ItemType.GRASS;
            stage.Items[63].Pos.Set(3, 0, -4); stage.Items[63].ItemType = ItemType.GRASS;
            stage.Items[64].Pos.Set(3, 0, -3); stage.Items[64].ItemType = ItemType.GEM;
            stage.Items[65].Pos.Set(3, 0, -2); stage.Items[65].ItemType = ItemType.GEM;
            stage.Items[66].Pos.Set(3, 0, -1); stage.Items[66].ItemType = ItemType.GEM;
            stage.Items[67].Pos.Set(3, 0, 0); stage.Items[67].ItemType = ItemType.GEM;
            stage.Items[68].Pos.Set(3, 0, 1); stage.Items[68].ItemType = ItemType.GEM;
            stage.Items[69].Pos.Set(3, 0, 2); stage.Items[69].ItemType = ItemType.GEM;
            stage.Items[70].Pos.Set(3, 0, 3); stage.Items[70].ItemType = ItemType.GEM;
            stage.Items[71].Pos.Set(3, 0, 4); stage.Items[71].ItemType = ItemType.GRASS;
            stage.Items[72].Pos.Set(4, 0, -4); stage.Items[72].ItemType = ItemType.GRASS;
            stage.Items[73].Pos.Set(4, 0, -3); stage.Items[73].ItemType = ItemType.GRASS;
            stage.Items[74].Pos.Set(4, 0, -2); stage.Items[74].ItemType = ItemType.GRASS;
            stage.Items[75].Pos.Set(4, 0, -1); stage.Items[75].ItemType = ItemType.GRASS;
            stage.Items[76].Pos.Set(4, 0, 0); stage.Items[76].ItemType = ItemType.GRASS;
            stage.Items[77].Pos.Set(4, 0, 1); stage.Items[77].ItemType = ItemType.GRASS;
            stage.Items[78].Pos.Set(4, 0, 2); stage.Items[78].ItemType = ItemType.GRASS;
            stage.Items[79].Pos.Set(4, 0, 3); stage.Items[79].ItemType = ItemType.GRASS;
            stage.Items[80].Pos.Set(4, 0, 4); stage.Items[80].ItemType = ItemType.GRASS;
            stages[12] = stage;

            stage = stages[13];
            stage.StageName = "大风车";
            stage.orders = new OrderType[5];
            stage.orders[0] = OrderType.MOVE_FORWARD;
            stage.orders[1] = OrderType.TURN_RIGHT;
            stage.orders[2] = OrderType.TRUN_LEFT;
            stage.orders[3] = OrderType.LOOP_MAIN;
            stage.orders[4] = OrderType.LOOP_TAIL;
            stage.Items = new ItemInfo[37];
            stage.Items[0].Pos.Set(-4, 0, 0); stage.Items[0].ItemType = ItemType.GRASS;
            stage.Items[1].Pos.Set(-4, 0, 1); stage.Items[1].ItemType = ItemType.GRASS;
            stage.Items[2].Pos.Set(-4, 0, 2); stage.Items[2].ItemType = ItemType.GRASS;
            stage.Items[3].Pos.Set(-4, 0, 3); stage.Items[3].ItemType = ItemType.GRASS;
            stage.Items[4].Pos.Set(-3, 0, -4); stage.Items[4].ItemType = ItemType.GRASS;
            stage.Items[5].Pos.Set(-3, 0, 0); stage.Items[5].ItemType = ItemType.GRASS;
            stage.Items[6].Pos.Set(-3, 0, 2); stage.Items[6].ItemType = ItemType.GRASS;
            stage.Items[7].Pos.Set(-2, 0, -4); stage.Items[7].ItemType = ItemType.GRASS;
            stage.Items[8].Pos.Set(-2, 0, -3); stage.Items[8].ItemType = ItemType.GRASS;
            stage.Items[9].Pos.Set(-2, 0, 0); stage.Items[9].ItemType = ItemType.GRASS;
            stage.Items[10].Pos.Set(-2, 0, 1); stage.Items[10].ItemType = ItemType.GRASS;
            stage.Items[11].Pos.Set(-1, 0, -4); stage.Items[11].ItemType = ItemType.GRASS;
            stage.Items[12].Pos.Set(-1, 0, -2); stage.Items[12].ItemType = ItemType.GRASS;
            stage.Items[13].Pos.Set(-1, 0, 0); stage.Items[13].ItemType = ItemType.GRASS;
            stage.Items[14].Pos.Set(0, 0, -4); stage.Items[14].ItemType = ItemType.GRASS;
            stage.Items[15].Pos.Set(0, 0, -3); stage.Items[15].ItemType = ItemType.GRASS;
            stage.Items[16].Pos.Set(0, 0, -2); stage.Items[16].ItemType = ItemType.GRASS;
            stage.Items[17].Pos.Set(0, 0, -1); stage.Items[17].ItemType = ItemType.GRASS;
            stage.Items[18].Pos.Set(0, 0, 0); stage.Items[18].ItemType = ItemType.ROCK;
            stage.Items[19].Pos.Set(0, 0, 1); stage.Items[19].ItemType = ItemType.GRASS;
            stage.Items[20].Pos.Set(0, 0, 2); stage.Items[20].ItemType = ItemType.GRASS;
            stage.Items[21].Pos.Set(0, 0, 3); stage.Items[21].ItemType = ItemType.GRASS;
            stage.Items[22].Pos.Set(0, 0, 4); stage.Items[22].ItemType = ItemType.GRASS;
            stage.Items[23].Pos.Set(1, 0, 0); stage.Items[23].ItemType = ItemType.GRASS;
            stage.Items[24].Pos.Set(1, 0, 2); stage.Items[24].ItemType = ItemType.GRASS;
            stage.Items[25].Pos.Set(1, 0, 4); stage.Items[25].ItemType = ItemType.GRASS;
            stage.Items[26].Pos.Set(2, 0, -1); stage.Items[26].ItemType = ItemType.GRASS;
            stage.Items[27].Pos.Set(2, 0, 0); stage.Items[27].ItemType = ItemType.GRASS;
            stage.Items[28].Pos.Set(2, 0, 3); stage.Items[28].ItemType = ItemType.GRASS;
            stage.Items[29].Pos.Set(2, 0, 4); stage.Items[29].ItemType = ItemType.GRASS;
            stage.Items[30].Pos.Set(3, 0, -2); stage.Items[30].ItemType = ItemType.GRASS;
            stage.Items[31].Pos.Set(3, 0, 0); stage.Items[31].ItemType = ItemType.GRASS;
            stage.Items[32].Pos.Set(3, 0, 4); stage.Items[32].ItemType = ItemType.GRASS;
            stage.Items[33].Pos.Set(4, 0, -3); stage.Items[33].ItemType = ItemType.GRASS;
            stage.Items[34].Pos.Set(4, 0, -2); stage.Items[34].ItemType = ItemType.GRASS;
            stage.Items[35].Pos.Set(4, 0, -1); stage.Items[35].ItemType = ItemType.GRASS;
            stage.Items[36].Pos.Set(4, 0, 0); stage.Items[36].ItemType = ItemType.GRASS;

            stages[13] = stage;

            stage = stages[14];
            stage.StageName = "HelloWorld";
            stage.orders = new OrderType[1];
            stage.orders[0] = OrderType.MOVE_FORWARD;
            stage.Items = new ItemInfo[11];
            stage.Items[0].Pos.Set(-4, 0, -3); stage.Items[0].ItemType = ItemType.GEM;
            stage.Items[1].Pos.Set(-4, 0, -2); stage.Items[1].ItemType = ItemType.ROCK;
            stage.Items[2].Pos.Set(-4, 0, -1); stage.Items[2].ItemType = ItemType.ROCK;
            stage.Items[3].Pos.Set(-3, 0, -4); stage.Items[3].ItemType = ItemType.ROCK;
            stage.Items[4].Pos.Set(-3, 0, -3); stage.Items[4].ItemType = ItemType.ROCK;
            stage.Items[5].Pos.Set(-3, 0, -2); stage.Items[5].ItemType = ItemType.ROCK;
            stage.Items[6].Pos.Set(-3, 0, -1); stage.Items[6].ItemType = ItemType.ROCK;
            stage.Items[7].Pos.Set(-2, 0, -4); stage.Items[7].ItemType = ItemType.ROCK;
            stage.Items[8].Pos.Set(-2, 0, -3); stage.Items[8].ItemType = ItemType.ROCK;
            stage.Items[9].Pos.Set(-2, 0, -2); stage.Items[9].ItemType = ItemType.ROCK;
            stage.Items[10].Pos.Set(-2, 0, -1); stage.Items[10].ItemType = ItemType.ROCK;
            stages[14] = stage;
        }
        StageDefine() {
            

        }

    }
}